# TCL File Generated by Component Editor 11.1sp2
# Mon Jul 23 23:35:27 JST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | m2vdec "MPEG2 Decoder" v1.0
# | @kimu_shu 2012.07.23.23:35:27
# | 
# | 
# | /home/shuta/projects/m2v_dec_impl/ip/m2vdec.v
# | 
# |    ./m2vdec.v syn, sim
# |    ./m2vfbagen.v syn, sim
# |    ./m2vctrl.v syn, sim
# |    ./m2vctrl_code.qip syn, sim
# |    ./m2vctrl_code.v syn, sim
# |    ./m2vidct.v syn, sim
# |    ./m2vidct_fram.qip syn, sim
# |    ./m2vidct_fram.v syn, sim
# |    ./m2vidct_iram.qip syn, sim
# |    ./m2vidct_iram.v syn, sim
# |    ./m2vidct_mult.qip syn, sim
# |    ./m2vidct_mult.v syn, sim
# |    ./m2vidct_rom.qip syn, sim
# |    ./m2vidct_rom.v syn, sim
# |    ./m2visdq.v syn, sim
# |    ./m2visdq_cmem.qip syn, sim
# |    ./m2visdq_cmem.v syn, sim
# |    ./m2visdq_dmem.qip syn, sim
# |    ./m2visdq_dmem.v syn, sim
# |    ./m2visdq_mult.qip syn, sim
# |    ./m2visdq_mult.v syn, sim
# |    ./m2vmc.v syn, sim
# |    ./m2vmc_fetch.qip syn, sim
# |    ./m2vmc_fetch.v syn, sim
# |    ./m2vmc_frameptr.qip syn, sim
# |    ./m2vmc_frameptr.v syn, sim
# |    ./m2vsdp.v syn, sim
# |    ./m2vside1.v syn, sim
# |    ./m2vside2.v syn, sim
# |    ./m2vside3.v syn, sim
# |    ./m2vside4.v syn, sim
# |    ./m2vstbuf.v syn, sim
# |    ./m2vstbuf_fifo.qip syn, sim
# |    ./m2vstbuf_fifo.v syn, sim
# |    ./m2vstbuf_shifter.qip syn, sim
# |    ./m2vstbuf_shifter.v syn, sim
# |    ./m2vvld.v syn, sim
# |    ./m2vvld_table.qip syn, sim
# |    ./m2vvld_table.v syn, sim
# |    ./m2vctrl_code.mif syn, sim
# |    ./m2vidct_fram.mif syn, sim
# |    ./m2vidct_rom.mif syn, sim
# |    ./m2visdq_cmem.mif syn, sim
# |    ./m2vmc_fetch.mif syn, sim
# |    ./m2vvld_table.mif syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module m2vdec
# | 
set_module_property NAME m2vdec
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "DSP/Video and Image Processing"
set_module_property AUTHOR @kimu_shu
set_module_property DISPLAY_NAME "MPEG2 Decoder"
set_module_property TOP_LEVEL_HDL_FILE m2vdec.v
set_module_property TOP_LEVEL_HDL_MODULE m2vdec
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME m2vdec
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file m2vdec.v {SYNTHESIS SIMULATION}
add_file m2vfbagen.v {SYNTHESIS SIMULATION}
add_file m2vctrl.v {SYNTHESIS SIMULATION}
add_file m2vctrl_code.qip {SYNTHESIS SIMULATION}
add_file m2vctrl_code.v {SYNTHESIS SIMULATION}
add_file m2vidct.v {SYNTHESIS SIMULATION}
add_file m2vidct_fram.qip {SYNTHESIS SIMULATION}
add_file m2vidct_fram.v {SYNTHESIS SIMULATION}
add_file m2vidct_iram.qip {SYNTHESIS SIMULATION}
add_file m2vidct_iram.v {SYNTHESIS SIMULATION}
add_file m2vidct_mult.qip {SYNTHESIS SIMULATION}
add_file m2vidct_mult.v {SYNTHESIS SIMULATION}
add_file m2vidct_rom.qip {SYNTHESIS SIMULATION}
add_file m2vidct_rom.v {SYNTHESIS SIMULATION}
add_file m2visdq.v {SYNTHESIS SIMULATION}
add_file m2visdq_cmem.qip {SYNTHESIS SIMULATION}
add_file m2visdq_cmem.v {SYNTHESIS SIMULATION}
add_file m2visdq_dmem.qip {SYNTHESIS SIMULATION}
add_file m2visdq_dmem.v {SYNTHESIS SIMULATION}
add_file m2visdq_mult.qip {SYNTHESIS SIMULATION}
add_file m2visdq_mult.v {SYNTHESIS SIMULATION}
add_file m2vmc.v {SYNTHESIS SIMULATION}
add_file m2vmc_fetch.qip {SYNTHESIS SIMULATION}
add_file m2vmc_fetch.v {SYNTHESIS SIMULATION}
add_file m2vmc_frameptr.qip {SYNTHESIS SIMULATION}
add_file m2vmc_frameptr.v {SYNTHESIS SIMULATION}
add_file m2vsdp.v {SYNTHESIS SIMULATION}
add_file m2vside1.v {SYNTHESIS SIMULATION}
add_file m2vside2.v {SYNTHESIS SIMULATION}
add_file m2vside3.v {SYNTHESIS SIMULATION}
add_file m2vside4.v {SYNTHESIS SIMULATION}
add_file m2vstbuf.v {SYNTHESIS SIMULATION}
add_file m2vstbuf_fifo.qip {SYNTHESIS SIMULATION}
add_file m2vstbuf_fifo.v {SYNTHESIS SIMULATION}
add_file m2vstbuf_shifter.qip {SYNTHESIS SIMULATION}
add_file m2vstbuf_shifter.v {SYNTHESIS SIMULATION}
add_file m2vvld.v {SYNTHESIS SIMULATION}
add_file m2vvld_table.qip {SYNTHESIS SIMULATION}
add_file m2vvld_table.v {SYNTHESIS SIMULATION}
add_file m2vctrl_code.mif {SYNTHESIS SIMULATION}
add_file m2vidct_fram.mif {SYNTHESIS SIMULATION}
add_file m2vidct_rom.mif {SYNTHESIS SIMULATION}
add_file m2visdq_cmem.mif {SYNTHESIS SIMULATION}
add_file m2vmc_fetch.mif {SYNTHESIS SIMULATION}
add_file m2vvld_table.mif {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter MEM_WIDTH INTEGER 23
set_parameter_property MEM_WIDTH DEFAULT_VALUE 23
set_parameter_property MEM_WIDTH DISPLAY_NAME MEM_WIDTH
set_parameter_property MEM_WIDTH TYPE INTEGER
set_parameter_property MEM_WIDTH UNITS None
set_parameter_property MEM_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MEM_WIDTH AFFECTS_GENERATION false
set_parameter_property MEM_WIDTH HDL_PARAMETER true
add_parameter MVH_WIDTH INTEGER 16
set_parameter_property MVH_WIDTH DEFAULT_VALUE 16
set_parameter_property MVH_WIDTH DISPLAY_NAME MVH_WIDTH
set_parameter_property MVH_WIDTH TYPE INTEGER
set_parameter_property MVH_WIDTH UNITS None
set_parameter_property MVH_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MVH_WIDTH AFFECTS_GENERATION false
set_parameter_property MVH_WIDTH HDL_PARAMETER true
add_parameter MVV_WIDTH INTEGER 15
set_parameter_property MVV_WIDTH DEFAULT_VALUE 15
set_parameter_property MVV_WIDTH DISPLAY_NAME MVV_WIDTH
set_parameter_property MVV_WIDTH TYPE INTEGER
set_parameter_property MVV_WIDTH UNITS None
set_parameter_property MVV_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MVV_WIDTH AFFECTS_GENERATION false
set_parameter_property MVV_WIDTH HDL_PARAMETER true
add_parameter MBX_WIDTH INTEGER 6
set_parameter_property MBX_WIDTH DEFAULT_VALUE 6
set_parameter_property MBX_WIDTH DISPLAY_NAME MBX_WIDTH
set_parameter_property MBX_WIDTH TYPE INTEGER
set_parameter_property MBX_WIDTH UNITS None
set_parameter_property MBX_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MBX_WIDTH AFFECTS_GENERATION false
set_parameter_property MBX_WIDTH HDL_PARAMETER true
add_parameter MBY_WIDTH INTEGER 5
set_parameter_property MBY_WIDTH DEFAULT_VALUE 5
set_parameter_property MBY_WIDTH DISPLAY_NAME MBY_WIDTH
set_parameter_property MBY_WIDTH TYPE INTEGER
set_parameter_property MBY_WIDTH UNITS None
set_parameter_property MBY_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MBY_WIDTH AFFECTS_GENERATION false
set_parameter_property MBY_WIDTH HDL_PARAMETER true
add_parameter MBX_ADDER INTEGER 6
set_parameter_property MBX_ADDER DEFAULT_VALUE 6
set_parameter_property MBX_ADDER DISPLAY_NAME MBX_ADDER
set_parameter_property MBX_ADDER TYPE INTEGER
set_parameter_property MBX_ADDER UNITS None
set_parameter_property MBX_ADDER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MBX_ADDER AFFECTS_GENERATION false
set_parameter_property MBX_ADDER HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock csi_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset rsi_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point control
# | 
add_interface control avalon end
set_interface_property control addressUnits WORDS
set_interface_property control associatedClock clock
set_interface_property control associatedReset reset
set_interface_property control bitsPerSymbol 8
set_interface_property control burstOnBurstBoundariesOnly false
set_interface_property control burstcountUnits WORDS
set_interface_property control explicitAddressSpan 0
set_interface_property control holdTime 0
set_interface_property control linewrapBursts false
set_interface_property control maximumPendingReadTransactions 1
set_interface_property control readLatency 0
set_interface_property control readWaitTime 1
set_interface_property control setupTime 0
set_interface_property control timingUnits Cycles
set_interface_property control writeWaitTime 0

set_interface_property control ENABLED true

add_interface_port control avs_control_address address Input 1
add_interface_port control avs_control_read read Input 1
add_interface_port control avs_control_readdata readdata Output 32
add_interface_port control avs_control_write write Input 1
add_interface_port control avs_control_writedata writedata Input 32
add_interface_port control avs_control_readdatavalid readdatavalid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq
# | 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint control
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset

set_interface_property irq ENABLED true

add_interface_port irq ins_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point stream
# | 
add_interface stream avalon_streaming end
set_interface_property stream associatedClock clock
set_interface_property stream associatedReset reset
set_interface_property stream dataBitsPerSymbol 8
set_interface_property stream errorDescriptor ""
set_interface_property stream firstSymbolInHighOrderBits true
set_interface_property stream maxChannel 0
set_interface_property stream readyLatency 0

set_interface_property stream ENABLED true

add_interface_port stream asi_stream_data data Input 8
add_interface_port stream asi_stream_ready ready Output 1
add_interface_port stream asi_stream_valid valid Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fbuf
# | 
add_interface fbuf avalon start
set_interface_property fbuf addressUnits SYMBOLS
set_interface_property fbuf associatedClock clock
set_interface_property fbuf associatedReset reset
set_interface_property fbuf bitsPerSymbol 8
set_interface_property fbuf burstOnBurstBoundariesOnly false
set_interface_property fbuf burstcountUnits WORDS
set_interface_property fbuf doStreamReads false
set_interface_property fbuf doStreamWrites false
set_interface_property fbuf holdTime 0
set_interface_property fbuf linewrapBursts false
set_interface_property fbuf maximumPendingReadTransactions 0
set_interface_property fbuf readLatency 0
set_interface_property fbuf readWaitTime 1
set_interface_property fbuf setupTime 0
set_interface_property fbuf timingUnits Cycles
set_interface_property fbuf writeWaitTime 0

set_interface_property fbuf ENABLED true

add_interface_port fbuf avm_fbuf_address address Output MEM_WIDTH
add_interface_port fbuf avm_fbuf_read read Output 1
add_interface_port fbuf avm_fbuf_readdata readdata Input 16
add_interface_port fbuf avm_fbuf_write write Output 1
add_interface_port fbuf avm_fbuf_writedata writedata Output 16
add_interface_port fbuf avm_fbuf_waitrequest waitrequest Input 1
add_interface_port fbuf avm_fbuf_readdatavalid readdatavalid Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fptr
# | 
add_interface fptr conduit end

set_interface_property fptr ENABLED true

add_interface_port fptr coe_fptr_address export Input MBX_WIDTH+MBY_WIDTH
add_interface_port fptr coe_fptr_updated export Output 1
add_interface_port fptr coe_fptr_number export Output 1
# | 
# +-----------------------------------
