# TCL File Generated by Component Editor 11.1sp2
# Tue Jul 24 07:08:14 JST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | m2vdd_hx8347a "HX8347A LCD Driver" v1.0
# | @kimu_shu 2012.07.24.07:08:14
# | HX8347A LCD Driver for m2vdec
# | 
# | /home/shuta/projects/m2v_dec_impl/ip/m2vdd_hx8347a.v
# | 
# |    ./m2vdd_hx8347a.v syn, sim
# |    ./m2vfbagen.v syn, sim
# |    ./ycbcr2rgb.v syn, sim
# |    ./m2vdd_hx8347a_buf.qip syn, sim
# |    ./m2vdd_hx8347a_buf.v syn, sim
# |    ./m2vdd_hx8347a_fifo.qip syn, sim
# |    ./m2vdd_hx8347a_fifo.v syn, sim
# |    ./ycbcr2rgb_mac.qip syn, sim
# |    ./ycbcr2rgb_mac.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module m2vdd_hx8347a
# | 
set_module_property DESCRIPTION "HX8347A LCD Driver for m2vdec"
set_module_property NAME m2vdd_hx8347a
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals/Display
set_module_property AUTHOR @kimu_shu
set_module_property DISPLAY_NAME "HX8347A LCD Driver"
set_module_property TOP_LEVEL_HDL_FILE m2vdd_hx8347a.v
set_module_property TOP_LEVEL_HDL_MODULE m2vdd_hx8347a
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME m2vdd_hx8347a
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file m2vdd_hx8347a.v {SYNTHESIS SIMULATION}
add_file m2vfbagen.v {SYNTHESIS SIMULATION}
add_file ycbcr2rgb.v {SYNTHESIS SIMULATION}
add_file m2vdd_hx8347a_buf.qip {SYNTHESIS SIMULATION}
add_file m2vdd_hx8347a_buf.v {SYNTHESIS SIMULATION}
add_file m2vdd_hx8347a_fifo.qip {SYNTHESIS SIMULATION}
add_file m2vdd_hx8347a_fifo.v {SYNTHESIS SIMULATION}
add_file ycbcr2rgb_mac.qip {SYNTHESIS SIMULATION}
add_file ycbcr2rgb_mac.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter MEM_WIDTH INTEGER 23
set_parameter_property MEM_WIDTH DEFAULT_VALUE 23
set_parameter_property MEM_WIDTH DISPLAY_NAME MEM_WIDTH
set_parameter_property MEM_WIDTH TYPE INTEGER
set_parameter_property MEM_WIDTH UNITS None
set_parameter_property MEM_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MEM_WIDTH AFFECTS_GENERATION false
set_parameter_property MEM_WIDTH HDL_PARAMETER true
add_parameter MBX_WIDTH INTEGER 6
set_parameter_property MBX_WIDTH DEFAULT_VALUE 6
set_parameter_property MBX_WIDTH DISPLAY_NAME MBX_WIDTH
set_parameter_property MBX_WIDTH TYPE INTEGER
set_parameter_property MBX_WIDTH UNITS None
set_parameter_property MBX_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MBX_WIDTH AFFECTS_GENERATION false
set_parameter_property MBX_WIDTH HDL_PARAMETER true
add_parameter MBY_WIDTH INTEGER 5
set_parameter_property MBY_WIDTH DEFAULT_VALUE 5
set_parameter_property MBY_WIDTH DISPLAY_NAME MBY_WIDTH
set_parameter_property MBY_WIDTH TYPE INTEGER
set_parameter_property MBY_WIDTH UNITS None
set_parameter_property MBY_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MBY_WIDTH AFFECTS_GENERATION false
set_parameter_property MBY_WIDTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl
# | 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 1
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0

set_interface_property ctrl ENABLED true

add_interface_port ctrl ctrl_read read Input 1
add_interface_port ctrl ctrl_readdata readdata Output 32
add_interface_port ctrl ctrl_write write Input 1
add_interface_port ctrl ctrl_writedata writedata Input 32
add_interface_port ctrl ctrl_waitrequest waitrequest Output 1
add_interface_port ctrl ctrl_readdatavalid readdatavalid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point lcd_clk
# | 
add_interface lcd_clk clock end
set_interface_property lcd_clk clockRate 0

set_interface_property lcd_clk ENABLED true

add_interface_port lcd_clk lcd_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point lcd
# | 
add_interface lcd conduit end

set_interface_property lcd ENABLED true

add_interface_port lcd lcd_reset_n export Output 1
add_interface_port lcd lcd_cs export Output 1
add_interface_port lcd lcd_rs export Output 1
add_interface_port lcd lcd_data export Bidir 16
add_interface_port lcd lcd_write_n export Output 1
add_interface_port lcd lcd_read_n export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fbuf
# | 
add_interface fbuf avalon start
set_interface_property fbuf addressUnits SYMBOLS
set_interface_property fbuf associatedClock clock
set_interface_property fbuf associatedReset reset
set_interface_property fbuf bitsPerSymbol 8
set_interface_property fbuf burstOnBurstBoundariesOnly false
set_interface_property fbuf burstcountUnits WORDS
set_interface_property fbuf doStreamReads false
set_interface_property fbuf doStreamWrites false
set_interface_property fbuf holdTime 0
set_interface_property fbuf linewrapBursts false
set_interface_property fbuf maximumPendingReadTransactions 1
set_interface_property fbuf readLatency 0
set_interface_property fbuf readWaitTime 1
set_interface_property fbuf setupTime 0
set_interface_property fbuf timingUnits Cycles
set_interface_property fbuf writeWaitTime 0

set_interface_property fbuf ENABLED true

add_interface_port fbuf fbuf_address address Output MEM_WIDTH
add_interface_port fbuf fbuf_read read Output 1
add_interface_port fbuf fbuf_readdata readdata Input 16
add_interface_port fbuf fbuf_write write Output 1
add_interface_port fbuf fbuf_writedata writedata Output 16
add_interface_port fbuf fbuf_waitrequest waitrequest Input 1
add_interface_port fbuf fbuf_readdatavalid readdatavalid Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fptr
# | 
add_interface fptr conduit end

set_interface_property fptr ENABLED true

add_interface_port fptr fptr_address export Output MBX_WIDTH+MBY_WIDTH
add_interface_port fptr fptr_updated export Input 1
add_interface_port fptr fptr_number export Input 1
# | 
# +-----------------------------------
