onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /demo_de0_sys_tb/demo_de0_sys_inst/nios2_qsys_0/i_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/csi_clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/rsi_reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avs_control_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avs_control_read
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avs_control_readdata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avs_control_write
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avs_control_writedata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avs_control_readdatavalid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/ins_irq
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/asi_stream_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/asi_stream_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/asi_stream_ready
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avm_fbuf_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avm_fbuf_read
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avm_fbuf_readdata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avm_fbuf_write
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avm_fbuf_writedata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avm_fbuf_waitrequest
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/avm_fbuf_readdatavalid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/coe_fptr_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/coe_fptr_updated
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/coe_fptr_number
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s0_data_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/pict_valid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/mvec_h_valid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/mvec_v_valid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s0_valid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s0_mb_x_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s0_mb_y_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s0_mb_qscode_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_block_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_coded_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/ready_isdq_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/run_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/level_sign_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/level_data_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/rl_valid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/qm_valid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/qm_custom_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/qm_intra_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/qm_value_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/ready_idct_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/ready_mc_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/softreset_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/block_start_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/block_end_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/picture_complete_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s0_enable_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_mb_intra_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_mb_qscode_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/sa_qstype_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/sa_dcprec_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/coef_sign_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/coef_data_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/coef_next_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_enable_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s2_enable_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/pixel_coded_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/pixel_addr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/pixel_data0_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/pixel_data1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/sa_iframe_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s2_mb_intra_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s3_mv_h_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s3_mv_v_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s3_mb_x_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s3_mb_y_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s3_mb_intra_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s3_block_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s3_coded_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s3_enable_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s4_mb_x_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s4_mb_y_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s4_mb_intra_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s4_block_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s4_coded_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s4_enable_w
add wave -noupdate -radix decimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_mv_h_w
add wave -noupdate -radix decimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_mv_v_w
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_mb_x_w
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s1_mb_y_w
add wave -noupdate -radix decimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s2_mv_h_w
add wave -noupdate -radix decimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s2_mv_v_w
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s2_mb_x_w
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s2_mb_y_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s2_block_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/s2_coded_w
add wave -noupdate -divider {New Divider}
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/lcd_clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/lcd_reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/lcd_cs
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/lcd_rs
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/lcd_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/lcd_write_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/lcd_read_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/ctrl_read
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/ctrl_readdata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/ctrl_write
add wave -noupdate -radix hexadecimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/ctrl_writedata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/ctrl_waitrequest
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/ctrl_readdatavalid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fbuf_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fbuf_read
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fbuf_readdata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fbuf_write
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fbuf_writedata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fbuf_waitrequest
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fbuf_readdatavalid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fptr_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fptr_updated
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fptr_number
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fifo_write_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fifo_wdata_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fifo_wfull_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fifo_read_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fifo_rdata_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/fifo_rempty_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/state_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/ctrl_read_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/softreset_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/max_mbx_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/max_mby_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/last_pxy_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/mbx_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/mby_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/next_mbx_w
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/next_mby_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/frpage_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/frchroma_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/frpxx2_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/frpxy_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/next_frpxx2_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/next_frpxy_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/bwpage_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/bwaddr_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/next_bwaddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/bwrite_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/brfull_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/brpixel_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/brluma_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/brchroma_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/brybuf_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/convert_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/brend_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/next_brpixel_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/braddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/buf_q_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/brcb_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/brcr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/rout_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/gout_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/bout_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/rgbvalid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/lcd_xwr_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdd_hx8347a_0/rempty_1d_r
add wave -noupdate -divider m2vctrl
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/control_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/control_read
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/control_readdata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/control_write
add wave -noupdate -radix hexadecimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/control_writedata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/control_readdatavalid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/irq
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/stream_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/stream_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/stream_ready
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/s0_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/pict_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/mvec_h_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/mvec_v_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/s0_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/s0_mb_x
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/s0_mb_y
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/s0_mb_qscode
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/s1_block
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/s1_coded
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/ready_isdq
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/run
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/level_sign
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/level_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rl_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/qm_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/qm_custom
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/qm_intra
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/qm_value
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/ready_idct
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/ready_mc
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/softreset
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/block_start
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/block_end
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/picture_complete
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/reg_status_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/reg_video_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/sel_status_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/ctrl_addr_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/ctrl_read_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/adata_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/bdata_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/softreset_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_rdbuf_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_align_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_vld_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_vldmask_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/vld_table_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_vldtbl_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_inout_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_rlpair_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/iaddress_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/ireadenable_w
add wave -noupdate -radix symbolic /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/instruction_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/adata_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/bdata_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/result_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_select_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_start_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_wait_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/custom_done_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/ioaddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/block_start_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/block_end_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/pic_complete_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/pictures_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/irq_seq_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/irq_pic_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/pause_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/error_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/video_wd_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/video_ht_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/frate_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/max_mbx_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/max_mby_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/cur_mbx_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/cur_mby_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/mbinc_en_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/slvert_en_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/addsub_mbx_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/mbxy_wait_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/sl_qs_code_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/mb_qs_code_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rlvld_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/symbol_data_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/symbol_valid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/symbol_nextbit_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/vld_width_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/vld_shift_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/buffer_data_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/buffer_valid_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rl_state_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rl_wmask_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rl_run_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rl_level_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rl_nextbit_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rl_valid_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/rl_shift1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/parser_shift_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/parser_width_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/parser_align_w
add wave -noupdate -divider m2visdq
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/softreset
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/ready_isdq
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/block_start
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/block_end
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/s0_enable
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/s1_coded
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/s1_mb_intra
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/s1_mb_qscode
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/sa_qstype
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/sa_dcprec
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/run
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/level_sign
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/level_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/rl_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/qm_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/qm_custom
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/qm_intra
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/qm_value
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/coef_sign
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/coef_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/coef_next
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/state_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/cust_qm_ni_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/cust_qm_i_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/qscale_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/wpos_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/rpos_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/wpage_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/empty_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/cvalid_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/clrcoef_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/mismatch_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/lastcoef_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/start_blk_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/end_blk_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/rlv_d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/sign_d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/head_pair_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/mult_cache_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/ovf_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/end_blkstate_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/next_wpos_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/next_rpos_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/cmem_addr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/cmem_dout_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/dmem_doutb_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/dc_mult_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/mult_a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/mult_b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/mult_result_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2visdq/clipped_w
add wave -noupdate -divider m2vidct
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/softreset
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ready_idct
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/block_start
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/s1_enable
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/s2_enable
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/coef_next
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/coef_sign
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/coef_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/pixel_coded
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/pixel_addr
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/pixel_data0
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/pixel_data1
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/busy_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/wpage_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/rpage_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/taddr_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/romdata_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/coefxp_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/coefxm_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/coefyp_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/coefym_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/t0idx_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/t1idx_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/midx_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/imed_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/save_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/askip_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/final_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/cm0res_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/cm1res_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ca0a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ca0b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ca0s_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ca1a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ca1b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ca1c_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ca1s_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ct0d_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ct1d_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/irhigh_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/iwrdata0_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/iwrdata1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/iwraddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/irdaddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/coldata_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/rm0res_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/rm1res_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ra0a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ra0b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ra0s_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ra1a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ra1b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ra1c_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/ra1s_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/rt0d_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/rt1d_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/teven_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/byteena_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/clip0_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/clip1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/fwraddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vidct/frdaddr_w
add wave -noupdate -divider m2vmc
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/softreset
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/ready_mc
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/block_start
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/picture_complete
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/pixel_coded
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/pixel_addr
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/pixel_data0
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/pixel_data1
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sa_iframe
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s2_mb_intra
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s2_enable
add wave -noupdate -radix decimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s3_mv_h
add wave -noupdate -radix decimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s3_mv_v
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s3_mb_x
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s3_mb_y
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s3_mb_intra
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s3_block
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s3_coded
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s3_enable
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s4_mb_x
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s4_mb_y
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s4_mb_intra
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s4_block
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s4_coded
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/s4_enable
add wave -noupdate -radix hexadecimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fbuf_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fbuf_read
add wave -noupdate -radix hexadecimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fbuf_readdata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fbuf_readdatavalid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fbuf_write
add wave -noupdate -radix hexadecimal /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fbuf_writedata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fbuf_waitrequest
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_updated
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_number
add wave -noupdate -radixenum symbolic /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/state_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/xhalf_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/xodd_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/yhalf_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_fetch_w
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/xref_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/yref_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/xref_1d_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/yref_1d_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/rxcnt_r
add wave -noupdate -radix unsigned /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/rycnt_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_fetch_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/use_1d_fptr_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fren_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/xraa_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/xrab_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/xrac_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/xrar_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/yraa_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/yrab_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/yrac_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/yrar_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_fetch_wait_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/frmbyx_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fb_fraddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/wxcnt_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/wycnt_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/wxcnt_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/wycnt_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/px1_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/px0_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/px1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/i0out_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/i1out_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum0a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum0b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum0r_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum1a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum1b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum1r_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum2a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum2b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum2r_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum3a_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum3b_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/sum3r_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fwaddr0_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fwaddr1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fwxen0_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fwxen1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fwen0_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fwen1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/mraddr_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/mrlast_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/mwaddr_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/mwen_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/waitreq_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/next_mraddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/mrdata0_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/mrdata1_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/p0sum_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/p1sum_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/p0clip_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/p1clip_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/p0clip_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/p1clip_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/mwmbyx_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fb_mwaddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_mix_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_update_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_page1_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_addrb_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fptr_addra_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/next_fpaddrb_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/last_fpaddrb_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fpn_datab_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fpn_douta_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fpu_datab_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vmc/fpu_douta_w
add wave -noupdate -divider m2vsdp
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/softreset
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/iaddress
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/ireadenable
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/instruction
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/custom_adata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/custom_bdata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/custom_result
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/custom_select
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/custom_start
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/custom_enable
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/custom_done
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/adata_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/bdata_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/ip_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/nop_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/stall_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/zf_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/cf_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/group_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/subcode_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/subsubcode_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/rd_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/imed_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/rs_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/fk_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/k_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/csel_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/kext_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/cst_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/mov_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/add_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/sub_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/and_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/or_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/not_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/shr_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/shl_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/usecf_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/store_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/jxz_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/jxc_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/jnx_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/stall_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/dojump_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/cst_mask_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/result_add_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/result_sub_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/result_and_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/result_or_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/result_not_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/result_shr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/result_shl_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/result_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_sdp/stsel_r
add wave -noupdate -divider fifo_0
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonmm_write_slave_waitrequest
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonst_source_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonst_source_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrclk_control_slave_irq
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrclk_control_slave_readdata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonmm_write_slave_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonmm_write_slave_write
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonmm_write_slave_writedata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonst_source_ready
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrclk_control_slave_address
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrclk_control_slave_read
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrclk_control_slave_write
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrclk_control_slave_writedata
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrclock
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonmm_map_data_in
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/avalonst_map_data_out
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/clock
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/empty
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/full
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/q
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/rdreq
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrreq
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/fifo_0/wrreq_driver
add wave -noupdate -divider m2vvld
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/softreset
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/vld_table
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/vld_decode
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/buffer_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/buffer_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/vld_width
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/vld_shift
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/symbol_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/symbol_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/symbol_nextbit
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/state_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/decode_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/table_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/shiftmask_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/shift6_1d_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/nextbits_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/taddr_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/nextbit_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/leaf_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/width_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_vld/tdata_w
add wave -noupdate -divider m2vstbuf
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/clk
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/reset_n
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/softreset
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/stream_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/stream_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/stream_ready
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/parser_shift
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/parser_width
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/parser_align
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/vld_width
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/vld_shift
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/buffer_data
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/buffer_valid
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/fetched_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/offset_r
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/wrfull_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/fifo_out_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/fifo_rdreq_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/fifo_rdempty_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/next_offset_w
add wave -noupdate /demo_de0_sys_tb/demo_de0_sys_inst/m2vdec_0/u_m2vctrl/u_stbuf/dataout_w
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {17395633161 ps} 0}
configure wave -namecolwidth 233
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {17395579496 ps} {17395932349 ps}
