onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /test_m2vctrl/u_dut/clk
add wave -noupdate /test_m2vctrl/u_dut/reset_n
add wave -noupdate /test_m2vctrl/u_dut/control_address
add wave -noupdate /test_m2vctrl/u_dut/control_read
add wave -noupdate -radix hexadecimal /test_m2vctrl/u_dut/control_readdata
add wave -noupdate /test_m2vctrl/u_dut/control_write
add wave -noupdate -radix hexadecimal /test_m2vctrl/u_dut/control_writedata
add wave -noupdate /test_m2vctrl/u_dut/control_readdatavalid
add wave -noupdate /test_m2vctrl/u_dut/irq
add wave -noupdate /test_m2vctrl/u_dut/stream_valid
add wave -noupdate /test_m2vctrl/u_dut/stream_data
add wave -noupdate /test_m2vctrl/u_dut/stream_ready
add wave -noupdate /test_m2vctrl/u_dut/s0_data
add wave -noupdate /test_m2vctrl/u_dut/pict_valid
add wave -noupdate /test_m2vctrl/u_dut/mvec_h_valid
add wave -noupdate /test_m2vctrl/u_dut/mvec_v_valid
add wave -noupdate /test_m2vctrl/u_dut/s0_valid
add wave -noupdate /test_m2vctrl/u_dut/s0_mb_x
add wave -noupdate /test_m2vctrl/u_dut/s0_mb_y
add wave -noupdate /test_m2vctrl/u_dut/s0_mb_qscode
add wave -noupdate /test_m2vctrl/u_dut/s1_block
add wave -noupdate /test_m2vctrl/u_dut/s1_coded
add wave -noupdate /test_m2vctrl/u_dut/ready_isdq
add wave -noupdate /test_m2vctrl/u_dut/run
add wave -noupdate /test_m2vctrl/u_dut/level_sign
add wave -noupdate /test_m2vctrl/u_dut/level_data
add wave -noupdate /test_m2vctrl/u_dut/rl_valid
add wave -noupdate /test_m2vctrl/u_dut/qm_valid
add wave -noupdate /test_m2vctrl/u_dut/qm_custom
add wave -noupdate /test_m2vctrl/u_dut/qm_intra
add wave -noupdate /test_m2vctrl/u_dut/qm_value
add wave -noupdate /test_m2vctrl/u_dut/ready_idct
add wave -noupdate /test_m2vctrl/u_dut/ready_mc
add wave -noupdate /test_m2vctrl/u_dut/softreset
add wave -noupdate /test_m2vctrl/u_dut/pre_block_start
add wave -noupdate /test_m2vctrl/u_dut/block_start
add wave -noupdate /test_m2vctrl/u_dut/block_end
add wave -noupdate /test_m2vctrl/u_dut/picture_complete
add wave -noupdate /test_m2vctrl/u_dut/reg_status_w
add wave -noupdate /test_m2vctrl/u_dut/reg_video_w
add wave -noupdate /test_m2vctrl/u_dut/sel_status_w
add wave -noupdate /test_m2vctrl/u_dut/ctrl_addr_1d_r
add wave -noupdate /test_m2vctrl/u_dut/ctrl_read_1d_r
add wave -noupdate /test_m2vctrl/u_dut/adata_r
add wave -noupdate /test_m2vctrl/u_dut/bdata_r
add wave -noupdate /test_m2vctrl/u_dut/softreset_r
add wave -noupdate /test_m2vctrl/u_dut/custom_rdbuf_r
add wave -noupdate /test_m2vctrl/u_dut/custom_align_r
add wave -noupdate /test_m2vctrl/u_dut/custom_vld_r
add wave -noupdate /test_m2vctrl/u_dut/custom_vldmask_r
add wave -noupdate /test_m2vctrl/u_dut/vld_table_r
add wave -noupdate /test_m2vctrl/u_dut/custom_vldtbl_r
add wave -noupdate /test_m2vctrl/u_dut/custom_inout_r
add wave -noupdate /test_m2vctrl/u_dut/custom_rlpair_r
add wave -noupdate -radix hexadecimal /test_m2vctrl/u_dut/iaddress_w
add wave -noupdate /test_m2vctrl/u_dut/ireadenable_w
add wave -noupdate -radix hexadecimal /test_m2vctrl/u_dut/instruction_w
add wave -noupdate /test_m2vctrl/u_dut/adata_w
add wave -noupdate /test_m2vctrl/u_dut/bdata_w
add wave -noupdate /test_m2vctrl/u_dut/result_w
add wave -noupdate /test_m2vctrl/u_dut/custom_select_w
add wave -noupdate /test_m2vctrl/u_dut/custom_start_w
add wave -noupdate /test_m2vctrl/u_dut/custom_wait_w
add wave -noupdate /test_m2vctrl/u_dut/custom_done_w
add wave -noupdate /test_m2vctrl/u_dut/ioaddr_w
add wave -noupdate /test_m2vctrl/u_dut/pre_block_start_r
add wave -noupdate /test_m2vctrl/u_dut/block_start_r
add wave -noupdate /test_m2vctrl/u_dut/block_end_r
add wave -noupdate /test_m2vctrl/u_dut/pic_complete_r
add wave -noupdate /test_m2vctrl/u_dut/pictures_r
add wave -noupdate /test_m2vctrl/u_dut/irq_seq_r
add wave -noupdate /test_m2vctrl/u_dut/irq_pic_r
add wave -noupdate /test_m2vctrl/u_dut/pause_r
add wave -noupdate /test_m2vctrl/u_dut/error_r
add wave -noupdate /test_m2vctrl/u_dut/video_wd_r
add wave -noupdate /test_m2vctrl/u_dut/video_ht_r
add wave -noupdate /test_m2vctrl/u_dut/frate_r
add wave -noupdate /test_m2vctrl/u_dut/max_mbx_r
add wave -noupdate /test_m2vctrl/u_dut/max_mby_r
add wave -noupdate /test_m2vctrl/u_dut/cur_mbx_r
add wave -noupdate /test_m2vctrl/u_dut/cur_mby_r
add wave -noupdate /test_m2vctrl/u_dut/mbinc_en_w
add wave -noupdate /test_m2vctrl/u_dut/slvert_en_w
add wave -noupdate /test_m2vctrl/u_dut/addsub_mbx_w
add wave -noupdate /test_m2vctrl/u_dut/mbxy_wait_w
add wave -noupdate /test_m2vctrl/u_dut/sl_qs_code_r
add wave -noupdate /test_m2vctrl/u_dut/mb_qs_code_r
add wave -noupdate /test_m2vctrl/u_dut/rlvld_w
add wave -noupdate /test_m2vctrl/u_dut/symbol_data_w
add wave -noupdate /test_m2vctrl/u_dut/symbol_valid_w
add wave -noupdate /test_m2vctrl/u_dut/symbol_nextbit_w
add wave -noupdate /test_m2vctrl/u_dut/vld_width_w
add wave -noupdate /test_m2vctrl/u_dut/vld_shift_w
add wave -noupdate /test_m2vctrl/u_dut/buffer_data_w
add wave -noupdate /test_m2vctrl/u_dut/buffer_valid_w
add wave -noupdate /test_m2vctrl/u_dut/rl_state_r
add wave -noupdate /test_m2vctrl/u_dut/rl_wmask_r
add wave -noupdate /test_m2vctrl/u_dut/rl_run_r
add wave -noupdate /test_m2vctrl/u_dut/rl_level_r
add wave -noupdate /test_m2vctrl/u_dut/rl_nextbit_r
add wave -noupdate /test_m2vctrl/u_dut/rl_valid_r
add wave -noupdate /test_m2vctrl/u_dut/rl_shift1_w
add wave -noupdate /test_m2vctrl/u_dut/parser_shift_w
add wave -noupdate /test_m2vctrl/u_dut/parser_width_w
add wave -noupdate /test_m2vctrl/u_dut/parser_align_w
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {227385 ps} 0}
configure wave -namecolwidth 179
configure wave -valuecolwidth 92
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {2505904 ps}
